from enum import StrEnum

from util import paths


class EventCategory(StrEnum):
    BUSINESS_AND_NETWORKING = "Business & Networking"
    MUSIC_AND_CONCERTS = "Music & Concerts"
    ARTS_AND_THEATRE = "Arts & Theatre"
    MARKETS_AND_FAIRS = "Markets & Fairs"
    FOOD_AND_DRINK = "Food & Drink"
    FESTIVALS = "Festivals"
    RELIGION_AND_SPIRITUALITY = "Religion & Spirituality"
    FILM_AND_MEDIA = "Film & Media"
    SPORTS_AND_FITNESS = "Sports & Fitness"
    HEALTH_AND_WELLNESS = "Health & Wellness"
    CONSERVATION_AND_NATURE = "Conservation & Nature"
    COMMUNITY_AND_CULTURE = "Community & Culture"
    HOBBIES_AND_INTERESTS = "Hobbies & Interests"
    GOVERNMENT_AND_POLITICS = "Government & Politics"
    KIDS_AND_PARENTS = "Kids & Parents"
    CLASSES_AND_WORKSHOPS = "Classes & Workshops"
    OTHER = "Other"


_CATEGORY_MAPPING: dict[str, EventCategory] = {
    "Community & Culture": EventCategory.COMMUNITY_AND_CULTURE,
    "Charity & Causes": EventCategory.COMMUNITY_AND_CULTURE,
    "Drum & Bass": EventCategory.MUSIC_AND_CONCERTS,
    "Markets and Fairs": EventCategory.MARKETS_AND_FAIRS,
    "TheaterEvent": EventCategory.ARTS_AND_THEATRE,
    "Jazz": EventCategory.MUSIC_AND_CONCERTS,
    "Games, Hobbies": EventCategory.HOBBIES_AND_INTERESTS,
    "Fun Runs & Walks": EventCategory.SPORTS_AND_FITNESS,
    "Film": EventCategory.FILM_AND_MEDIA,
    "Festival": EventCategory.FESTIVALS,
    "World": EventCategory.MUSIC_AND_CONCERTS,
    "Dance": EventCategory.CLASSES_AND_WORKSHOPS,
    "School Activities": EventCategory.CLASSES_AND_WORKSHOPS,
    "Family & Lifestyle": EventCategory.COMMUNITY_AND_CULTURE,
    "Quiz, Karaoke": EventCategory.HOBBIES_AND_INTERESTS,
    "MusicEvent": EventCategory.MUSIC_AND_CONCERTS,
    "Music": EventCategory.MUSIC_AND_CONCERTS,
    "Music Festivals": EventCategory.MUSIC_AND_CONCERTS,
    "Swing, Big Bands": EventCategory.MUSIC_AND_CONCERTS,
    "Choir, Vocal Music": EventCategory.MUSIC_AND_CONCERTS,
    "Family & Education": EventCategory.CLASSES_AND_WORKSHOPS,
    "Festivals": EventCategory.FESTIVALS,
    "Government & Politics": EventCategory.GOVERNMENT_AND_POLITICS,
    "Concerts": EventCategory.MUSIC_AND_CONCERTS,
    "Mind & Body": EventCategory.HEALTH_AND_WELLNESS,
    "Bar DJs": EventCategory.MUSIC_AND_CONCERTS,
    "Arts+%26+Theatre": EventCategory.ARTS_AND_THEATRE,
    "Hobbies & Special Interest": EventCategory.HOBBIES_AND_INTERESTS,
    "Country": EventCategory.MUSIC_AND_CONCERTS,
    "Performing & Visual Arts": EventCategory.ARTS_AND_THEATRE,
    "Sports & Fitness": EventCategory.SPORTS_AND_FITNESS,
    "Business & Professional": EventCategory.BUSINESS_AND_NETWORKING,
    "Religion & Spirituality": EventCategory.RELIGION_AND_SPIRITUALITY,
    "Literary": EventCategory.ARTS_AND_THEATRE,
    "Food & Drink": EventCategory.FOOD_AND_DRINK,
    "Arts and Crafts": EventCategory.HOBBIES_AND_INTERESTS,
    "Rock": EventCategory.MUSIC_AND_CONCERTS,
    "Classical Music": EventCategory.MUSIC_AND_CONCERTS,
    "Drag Performance": EventCategory.ARTS_AND_THEATRE,
    "Singer-Songwriter": EventCategory.MUSIC_AND_CONCERTS,
    "Sports": EventCategory.SPORTS_AND_FITNESS,
    "Commemorations, Ceremonies": EventCategory.COMMUNITY_AND_CULTURE,
    "Comedy": EventCategory.ARTS_AND_THEATRE,
    "Film, Media & Entertainment": EventCategory.FILM_AND_MEDIA,
    "Ethnic, Multicultural": EventCategory.COMMUNITY_AND_CULTURE,
    "Exhibitions": EventCategory.ARTS_AND_THEATRE,
    "Education": EventCategory.CLASSES_AND_WORKSHOPS,
    "Health & Wellness": EventCategory.HEALTH_AND_WELLNESS,
    "Science & Technology": EventCategory.CLASSES_AND_WORKSHOPS,
    "Public Talks & Tours": EventCategory.CLASSES_AND_WORKSHOPS,
    "Circus": EventCategory.KIDS_AND_PARENTS,
    "Fashion & Beauty": EventCategory.COMMUNITY_AND_CULTURE,
    "Theatre": EventCategory.ARTS_AND_THEATRE,
    "Food, Gourmet, Wine": EventCategory.FOOD_AND_DRINK,
    "Soccer": EventCategory.SPORTS_AND_FITNESS,
    "Children, Kids, Holidays": EventCategory.KIDS_AND_PARENTS,
    "Kids & Parents": EventCategory.KIDS_AND_PARENTS,
    "Family Friendly": EventCategory.KIDS_AND_PARENTS,
    "Kids": EventCategory.KIDS_AND_PARENTS,
    "Covers, Tribute Bands": EventCategory.MUSIC_AND_CONCERTS,
    "Gardening": EventCategory.HOBBIES_AND_INTERESTS,
    "Alumni, Associations, Clubs": EventCategory.HOBBIES_AND_INTERESTS,
    "Diving": EventCategory.HOBBIES_AND_INTERESTS,
    "Concert": EventCategory.MUSIC_AND_CONCERTS,
    "Professional networking": EventCategory.BUSINESS_AND_NETWORKING,
    "Foods": EventCategory.FOOD_AND_DRINK,
    "Drinks": EventCategory.FOOD_AND_DRINK,
    "Music and audio": EventCategory.MUSIC_AND_CONCERTS,
    "Parties": EventCategory.COMMUNITY_AND_CULTURE,
    "Healthy living and self-care": EventCategory.HEALTH_AND_WELLNESS,
    "Classics": EventCategory.MUSIC_AND_CONCERTS,
    "Fitness & workouts": EventCategory.SPORTS_AND_FITNESS,
    "Shopping": EventCategory.COMMUNITY_AND_CULTURE,
    "Games": EventCategory.HOBBIES_AND_INTERESTS,
    "TV and films": EventCategory.FILM_AND_MEDIA,
    "Visual arts": EventCategory.ARTS_AND_THEATRE,
    "Religions": EventCategory.RELIGION_AND_SPIRITUALITY,
    "Crafts": EventCategory.HOBBIES_AND_INTERESTS,
    "Social issues": EventCategory.COMMUNITY_AND_CULTURE,
    "Health & medical": EventCategory.HEALTH_AND_WELLNESS,
    "SportsEvent": EventCategory.SPORTS_AND_FITNESS,
    "Home and garden": EventCategory.HOBBIES_AND_INTERESTS,
    "Pop": EventCategory.MUSIC_AND_CONCERTS,
    "Charity, Fundraisers": EventCategory.COMMUNITY_AND_CULTURE,
    "Open Mic, Jams": EventCategory.MUSIC_AND_CONCERTS,
    "Skating": EventCategory.SPORTS_AND_FITNESS,
    "Alternative, Indie": EventCategory.MUSIC_AND_CONCERTS,
    "Folk": EventCategory.MUSIC_AND_CONCERTS,
    "Family Entertainment": EventCategory.COMMUNITY_AND_CULTURE,
    "Cabaret, Burlesque": EventCategory.MUSIC_AND_CONCERTS,
    "Socials, Singles, Balls": EventCategory.COMMUNITY_AND_CULTURE,
    "R&B, Soul": EventCategory.MUSIC_AND_CONCERTS,
    "Funk": EventCategory.MUSIC_AND_CONCERTS,
    "Arts & Theatre": EventCategory.ARTS_AND_THEATRE,
    "Hobbies & Interests": EventCategory.HOBBIES_AND_INTERESTS,
    "Film & Media": EventCategory.FILM_AND_MEDIA,
    "Music & Concerts": EventCategory.MUSIC_AND_CONCERTS,
    "Classes & Workshops": EventCategory.CLASSES_AND_WORKSHOPS,
    "Business & Networking": EventCategory.OTHER,
    "Auto, Boat & Air": EventCategory.OTHER,
    "Experiences": EventCategory.OTHER,
    "Cycling": EventCategory.SPORTS_AND_FITNESS,
    "Markets & Fairs": EventCategory.MARKETS_AND_FAIRS,
    "Variety Concerts": EventCategory.MUSIC_AND_CONCERTS,
    "Adventure, Extreme": EventCategory.HOBBIES_AND_INTERESTS,
    "Electronica": EventCategory.OTHER,
    "Musicals": EventCategory.MUSIC_AND_CONCERTS,
    "Conservation & Nature": EventCategory.CONSERVATION_AND_NATURE,
    "Hip Hop, Rap": EventCategory.MUSIC_AND_CONCERTS,
    "Food+%26+Drink": EventCategory.FOOD_AND_DRINK,
    "Food & Drinks": EventCategory.FOOD_AND_DRINK,
    "Gaming": EventCategory.HOBBIES_AND_INTERESTS,
    "Photography": EventCategory.HOBBIES_AND_INTERESTS,
    "Speed Dating": EventCategory.COMMUNITY_AND_CULTURE,
    "Technology": EventCategory.OTHER,
    "Trips & Adventure": EventCategory.HOBBIES_AND_INTERESTS,
    "Blues": EventCategory.MUSIC_AND_CONCERTS,
    "Snooker, Billiards, Pool": EventCategory.HOBBIES_AND_INTERESTS,
    "Speak": EventCategory.CLASSES_AND_WORKSHOPS,
    "Write": EventCategory.CLASSES_AND_WORKSHOPS,
    "Look": EventCategory.HOBBIES_AND_INTERESTS,
    "Make": EventCategory.HOBBIES_AND_INTERESTS,
    "Taste": EventCategory.FOOD_AND_DRINK,
    "Explore": EventCategory.HOBBIES_AND_INTERESTS,
    "Play": EventCategory.KIDS_AND_PARENTS,
    "Develop": EventCategory.CLASSES_AND_WORKSHOPS,
    "Free courses": EventCategory.CLASSES_AND_WORKSHOPS,
    "Business": EventCategory.BUSINESS_AND_NETWORKING,
    "Health": EventCategory.HEALTH_AND_WELLNESS,
    "Community": EventCategory.COMMUNITY_AND_CULTURE,
    "Hobbies": EventCategory.HOBBIES_AND_INTERESTS,
    "Home & Lifestyle": EventCategory.HOBBIES_AND_INTERESTS,
    "Government": EventCategory.GOVERNMENT_AND_POLITICS,
    "Science & Tech": EventCategory.CLASSES_AND_WORKSHOPS,
    "Holidays": EventCategory.KIDS_AND_PARENTS,
    "Travel & Outdoor": EventCategory.OTHER,
    "Photography & Visual Arts": EventCategory.HOBBIES_AND_INTERESTS,
    "Spirituality": EventCategory.RELIGION_AND_SPIRITUALITY,
    "Martial Arts": EventCategory.HOBBIES_AND_INTERESTS,
    "Fashion": EventCategory.HOBBIES_AND_INTERESTS,
    "Lifestyle Shows, Expos": EventCategory.HEALTH_AND_WELLNESS,
    "Marathon, Running": EventCategory.HOBBIES_AND_INTERESTS,
    "Fitness": EventCategory.HOBBIES_AND_INTERESTS,
    "Ballet": EventCategory.ARTS_AND_THEATRE,
    "Wrestling": EventCategory.HOBBIES_AND_INTERESTS,
    "Classic Rock": EventCategory.MUSIC_AND_CONCERTS,
    "Dance Sport": EventCategory.HOBBIES_AND_INTERESTS,
    "Opera": EventCategory.MUSIC_AND_CONCERTS,
    "Latin": EventCategory.HOBBIES_AND_INTERESTS,
    "Reggae": EventCategory.MUSIC_AND_CONCERTS,
    "Swimming": EventCategory.HOBBIES_AND_INTERESTS,
    "Rugby Union": EventCategory.SPORTS_AND_FITNESS,
    "Dub, Roots": EventCategory.MUSIC_AND_CONCERTS,
    "Punk": EventCategory.MUSIC_AND_CONCERTS,
    "Public Speaking": EventCategory.CLASSES_AND_WORKSHOPS,
    "Relaxation": EventCategory.HEALTH_AND_WELLNESS,
    "Drawing & Painting": EventCategory.CLASSES_AND_WORKSHOPS,
    "Wine Tasting": EventCategory.FOOD_AND_DRINK,
    "Product Management": EventCategory.BUSINESS_AND_NETWORKING,
    "Metal": EventCategory.MUSIC_AND_CONCERTS,
    "Bible Study": EventCategory.RELIGION_AND_SPIRITUALITY,
    "Employment Opportunities": EventCategory.BUSINESS_AND_NETWORKING,
    "Catering": EventCategory.FOOD_AND_DRINK,
    "Hiking": EventCategory.SPORTS_AND_FITNESS,
    "Alternative Music": EventCategory.MUSIC_AND_CONCERTS,
    "Pop-Ups": EventCategory.MARKETS_AND_FAIRS,
    "Chocolates": EventCategory.FOOD_AND_DRINK,
    "Marathons": EventCategory.SPORTS_AND_FITNESS,
    "Charities": EventCategory.COMMUNITY_AND_CULTURE,
    "Punk Shows": EventCategory.MUSIC_AND_CONCERTS,
    "Cooking": EventCategory.CLASSES_AND_WORKSHOPS,
    "Salsa": EventCategory.CLASSES_AND_WORKSHOPS,
    "Chess": EventCategory.HOBBIES_AND_INTERESTS,
    "Street Fairs": EventCategory.MARKETS_AND_FAIRS,
    "Writing": EventCategory.CLASSES_AND_WORKSHOPS,
    "Exercise": EventCategory.SPORTS_AND_FITNESS,
    "Family Fun": EventCategory.KIDS_AND_PARENTS,
    "Meet & Greet": EventCategory.BUSINESS_AND_NETWORKING,
    "Rock Music": EventCategory.MUSIC_AND_CONCERTS,
    "Performances": EventCategory.ARTS_AND_THEATRE,
    "Violin": EventCategory.MUSIC_AND_CONCERTS,
    "Pasta": EventCategory.FOOD_AND_DRINK,
    "Finance": EventCategory.BUSINESS_AND_NETWORKING,
    "Flute": EventCategory.MUSIC_AND_CONCERTS,
    "Burger": EventCategory.FOOD_AND_DRINK,
    "Pottery": EventCategory.CLASSES_AND_WORKSHOPS,
    "Piano Concerts": EventCategory.MUSIC_AND_CONCERTS,
    "Christian": EventCategory.RELIGION_AND_SPIRITUALITY,
    "Sea Food": EventCategory.FOOD_AND_DRINK,
    "Acoustic Music": EventCategory.MUSIC_AND_CONCERTS,
    "Fine Arts": EventCategory.ARTS_AND_THEATRE,
    "Meditation": EventCategory.HEALTH_AND_WELLNESS,
    "Classical Concert": EventCategory.MUSIC_AND_CONCERTS,
    "Environmentalism": EventCategory.CONSERVATION_AND_NATURE,
    "Night Markets": EventCategory.MARKETS_AND_FAIRS,
    "Wine": EventCategory.FOOD_AND_DRINK,
    "Vegan": EventCategory.FOOD_AND_DRINK,
    "Mindfulness": EventCategory.HEALTH_AND_WELLNESS,
    "Mountain Biking": EventCategory.SPORTS_AND_FITNESS,
    "Motorsport": EventCategory.SPORTS_AND_FITNESS,
    "Food Trucks": EventCategory.FOOD_AND_DRINK,
    "Christmas Markets & Fairs": EventCategory.MARKETS_AND_FAIRS,
    "Market": EventCategory.MARKETS_AND_FAIRS,
    "Other": EventCategory.OTHER,
}


class CategoryMapping:
    @staticmethod
    def map_category(category: str) -> EventCategory:
        mapped = _CATEGORY_MAPPING.get(category)
        if mapped is not None:
            return mapped
        with open(paths.data_path("missingcats.txt"), "a") as f:
            f.write(category)
            f.write("\n")
            print(f"Category Not Found {category}")
        return EventCategory.OTHER
