class CategoryMapping:
    @staticmethod
    def map_category(category: str) -> str:
        # 'Education & Learning',
        # 'Business & Networking',
        # 'Music & Concerts',
        # 'Arts & Theatre',
        # 'Markets & Fairs',
        # 'Food & Drink',
        # 'Festivals',
        # 'Religion & Spirituality',
        # 'Film & Media',
        # 'Sports & Fitness',
        # 'Health & Wellness',
        # 'Conservation & Environment',
        # 'Community & Culture',
        # 'Hobbies & Interests',
        # 'Government & Politics'
        # 'Family Friendly'
        # 'Classes & Workshops'

        category_mapping = {
            "Classes & Workshops": "Classes & Workshops",
            "Community & Culture": "Community & Culture",
            "Charity & Causes": "Community & Culture",
            "Drum & Bass": "Music & Concerts",
            "Markets and Fairs": "Markets & Fairs",
            "TheaterEvent": "Arts & Theatre",
            "Jazz": "Music & Concerts",
            "Games, Hobbies": "Hobbies & Interests",
            "Fun Runs & Walks": "Sports & Fitness",
            "Film": "Film & Media",
            "Festival": "Festivals",
            "World": "Music & Concerts",
            "Dance": "Classes & Workshops",
            "School Activities": "Education & Learning",
            "Family & Lifestyle": "Community & Culture",
            "Quiz, Karaoke": "Hobbies & Interests",
            "MusicEvent": "Music & Concerts",
            "Music": "Music & Concerts",
            "Music Festivals": "Music & Concerts",
            "Swing, Big Bands": "Music & Concerts",
            "Choir, Vocal Music": "Music & Concerts",
            "Family & Education": "Education & Learning",
            "Festivals": "Festivals",
            "Government & Politics": "Government & Politics",
            "Concerts": "Music & Concerts",
            "Mind & Body": "Health & Wellness",
            "Bar DJs": "Music & Concerts",
            "Arts+%26+Theatre": "Arts & Theatre",
            "Hobbies & Special Interest": "Hobbies & Interests",
            "Country": "Music & Concerts",
            "Performing & Visual Arts": "Arts & Theatre",
            "Sports & Fitness": "Sports & Fitness",
            "Business & Professional": "Business & Networking",
            "Religion & Spirituality": "Religion & Spirituality",
            "Literary": "Arts & Theatre",
            "Food & Drink": "Food & Drink",
            "Arts and Crafts": "Hobbies & Interests",
            "Rock": "Music & Concerts",
            "Classical Music": "Music & Concerts",
            "Drag Performance": "Arts & Theatre",
            "Singer-Songwriter": "Music & Concerts",
            "Sports": "Sports & Fitness",
            "Commemorations, Ceremonies": "Community & Culture",
            "Comedy": "Arts & Theatre",
            "Film, Media & Entertainment": "Film & Media",
            "Ethnic, Multicultural": "Community & Culture",
            "Exhibitions": "Arts & Theatre",
            "Education": "Education & Learning",
            "Health & Wellness": "Health & Wellness",
            "Science & Technology": "Education & Learning",
            "Public Talks & Tours": "Education & Learning",
            "Circus": "Family Friendly",
            "Fashion & Beauty": "Community & Culture",
            "Theatre": "Arts & Theatre",
            "Food, Gourmet, Wine": "Food & Drink",
            "Soccer": "Sports & Fitness",
            "Children, Kids, Holidays": "Family Friendly",
            "Family Friendly": "Family Friendly",
            "Kids": "Family Friendly",
            "Covers, Tribute Bands": "Music & Concerts",
            "Gardening": "Hobbies & Interests",
            "Alumni, Associations, Clubs": "Hobbies & Interests",
            "Diving":"Hobbies & Interests",
            "Concert": "Music & Concerts",
            "Professional networking": "Business & Networking",
            "Foods": "Food & Drink",
            "Drinks": "Food & Drink",
            "Music and audio": "Music & Concerts",
            "Parties": "Community & Culture",
            "Healthy living and self-care": "Health & Wellness",
            "Classics": "Music & Concerts",
            "Fitness & workouts": "Sports & Fitness",
            "Shopping": "Community & Culture",
            "Games": "Hobbies & Interests",
            "TV and films": "Film & Media",
            "Visual arts": "Arts & Theatre",
            "Religions": "Religion & Spirituality",
            "Crafts": "Hobbies & Interests",
            "Social issues": "Community & Culture",
            "Health & medical": "Health & Wellness",
            "SportsEvent": "Sports & Fitness",
            "Home and garden": "Hobbies & Interests",
            "Pop": "Music & Concerts",
            "Charity, Fundraisers": "Community & Culture",
            "Open Mic, Jams": "Music & Concerts",
            "Skating": "Sports & Fitness",
            "Alternative, Indie": "Music & Concerts",
            "Folk": "Music & Concerts",
            "Family Entertainment": "Community & Culture",
            "Cabaret, Burlesque": "Music & Concerts",
            "Socials, Singles, Balls": "Community & Culture",
            "R&B, Soul": "Music & Concerts",
            "Funk": "Music & Concerts",
            "Arts & Theatre": "Arts & Theatre",
            "Hobbies & Interests": "Hobbies & Interests",
            "Film & Media": "Film & Media",
            "Music & Concerts": "Music & Concerts",
            "Education & Learning": "Education & Learning",
            "Business & Networking": "Other",
            "Auto, Boat & Air": "Other",
            "Experiences": "Other",
            "Cycling": "Sports & Fitness",
            "Markets & Fairs": "Markets & Fairs",
            "Variety Concerts": "Music & Concerts",
            "Adventure, Extreme": "Hobbies & Interests",
            "Electronica": "Other",
            "Musicals": "Music & Concerts",
            "Conservation & Environment": "Conservation & Environment",
            "Hip Hop, Rap": "Music & Concerts",
            "Food+%26+Drink": "Food & Drink",
            "Blues": "Music & Concerts",
            "Snooker, Billiards, Pool": "Hobbies & Interests",
            "Speak": "Education & Learning",
            "Write": "Education & Learning",
            "Look": "Hobbies & Interests",
            "Make": "Hobbies & Interests",
            "Taste": "Food & Drink",
            "Explore": "Hobbies & Interests",
            "Play": "Family Friendly",
            "Develop": "Education & Learning",
            "Free courses": "Education & Learning",
            "Business": "Business & Networking",
            "Health": "Health & Wellness",
            "Community": "Community & Culture",
            "Hobbies": "Hobbies & Interests",
            "Home & Lifestyle": "Hobbies & Interests",
            "Government": "Government & Politics",
            "Science & Tech": "Education & Learning",
            "Holidays": "Family Friendly",
            "Travel & Outdoor": "Other",
            "Photography & Visual Arts": "Hobbies & Interests",
            "Spirituality": "Religion & Spirituality",
            "Martial Arts": "Hobbies & Interests",
            "Fashion": "Hobbies & Interests",
            "Lifestyle Shows, Expos": "Health & Wellness",
            "Marathon, Running": "Hobbies & Interests",
            "Fitness": "Hobbies & Interests",
            "Ballet": "Arts & Theatre",
            "Wrestling": "Hobbies & Interests",
            "Classic Rock": "Music & Concerts",
            "Dance Sport": "Hobbies & Interests",
            "Opera": "Music & Concerts",
            "Latin": "Hobbies & Interests",
            "Reggae": "Music & Concerts",
            "Swimming": "Hobbies & Interests",
            "Rugby Union": "Sports & Fitness",
            "Dub, Roots": "Music & Concerts",
            "Punk": "Music & Concerts",
            "Public Speaking": "Education & Learning",
            "Relaxation": "Health & Wellness",
            "Drawing & Painting": "Classes & Workshops",
            "Wine Tasting": "Food & Drink",
            "Product Management": "Business & Networking",
            "Metal": "Music & Concerts",
            "Bible Study": "Religion & Spirituality",
            "Employment Opportunities": "Business & Networking",
            "Catering": "Food & Drink",
            "Hiking": "Sports & Fitness",
            "Alternative Music": "Music & Concerts",
            "Pop-Ups": "Markets & Fairs",
            "Chocolates": "Food & Drink",
            "Marathons": "Sports & Fitness",
            "Charities": "Community & Culture",
            "Punk Shows": "Music & Concerts",
            "Cooking": "Classes & Workshops",
            "Salsa": "Classes & Workshops",
            "Chess": "Hobbies & Interests",
            "Street Fairs": "Markets & Fairs",
            "Writing": "Education & Learning",
            "Exercise": "Sports & Fitness",
            "Family Fun": "Family Friendly",
            "Meet & Greet": "Business & Networking",
            "Rock Music": "Music & Concerts",
            "Performances": "Arts & Theatre",
            "Violin": "Music & Concerts",
            "Pasta": "Food & Drink",
            "Finance": "Business & Networking",
            "Flute": "Music & Concerts",
            "Burger": "Food & Drink",
            "Pottery": "Classes & Workshops",
            "Piano Concerts": "Music & Concerts",
            "Christian": "Religion & Spirituality",
            "Sea Food": "Food & Drink",
            "Acoustic Music": "Music & Concerts",
            "Fine Arts": "Arts & Theatre",
            "Meditation": "Health & Wellness",
            "Classical Concert": "Music & Concerts",
            "Environmentalism": "Conservation & Environment",
            "Night Markets": "Markets & Fairs",
            "Wine": "Food & Drink",
            "Vegan": "Food & Drink",
            "Mindfulness": "Health & Wellness",
            "Mountain Biking": "Sports & Fitness",
            "Food Trucks": "Food & Drink",
            "Christmas Markets & Fairs": "Markets & Fairs",
            "Market": "Markets & Fairs",
            "Other": "Other"
        }
        cat = category_mapping.get(category)
        if cat:
            return cat
        with open("missingcats.txt", "a") as f:
            f.write(category)
            f.write("\n")
            print(f"Category Not Found {category}")
        return "Other"