class CategoryMapping:
    @staticmethod
    def map_category(category: str):
        category_mapping = {
            "Community & Culture": "Community & Culture",
            "Charity & Causes": "Community & Culture",
            "Drum & Bass": "Music & Concerts",
            "Markets and Fairs": "Other",
            "TheaterEvent": "Arts & Theatre",
            "Jazz": "Music & Concerts",
            "Games, Hobbies": "Hobbies & Interests",
            "Fun Runs & Walks": "Sports & Fitness",
            "Film": "Film & Media",
            "Festival": "Other",
            "World": "Music & Concerts",
            "Dance": "Music & Concerts",
            "School Activities": "Education & Learning",
            "Family & Lifestyle": "Community & Culture",
            "Quiz, Karaoke": "Hobbies & Interests",
            "MusicEvent": "Music & Concerts",
            "Music": "Music & Concerts",
            "Music Festivals": "Music & Concerts",
            "Swing, Big Bands": "Music & Concerts",
            "Choir, Vocal Music": "Music & Concerts",
            "Family & Education": "Education & Learning",
            "Festivals": "Other",
            "Government & Politics": "Community & Culture",
            "Concerts": "Music & Concerts",
            "Mind & Body": "Health & Wellness",
            "Bar DJs": "Music & Concerts",
            "Arts+%26+Theatre": "Arts & Theatre",
            "Hobbies & Special Interest": "Hobbies & Interests",
            "Country": "Music & Concerts",
            "Performing & Visual Arts": "Arts & Theatre",
            "Sports & Fitness": "Sports & Fitness",
            "Business & Professional": "Other",
            "Religion & Spirituality": "Other",
            "Literary": "Other",
            "Food & Drink": "Food & Drink",
            "Arts and Crafts": "Hobbies & Interests",
            "Rock": "Music & Concerts",
            "Classical Music": "Music & Concerts",
            "Drag Performance": "Music & Concerts",
            "Singer-Songwriter": "Music & Concerts",
            "Sports": "Sports & Fitness",
            "Commemorations, Ceremonies": "Community & Culture",
            "Comedy": "Arts & Theatre",
            "Other": "Other",
            "Film, Media & Entertainment": "Film & Media",
            "Ethnic, Multicultural": "Community & Culture",
            "Exhibitions": "Arts & Theatre",
            "Education": "Education & Learning",
            "Health & Wellness": "Health & Wellness",
            "Science & Technology": "Education & Learning",
            "Public Talks & Tours": "Education & Learning",
            "Circus": "Arts & Theatre",
            "Fashion & Beauty": "Community & Culture",
            "Theatre": "Arts & Theatre",
            "Food, Gourmet, Wine": "Food & Drink",
            "Soccer": "Sports & Fitness",
            "Children, Kids, Holidays": "Community & Culture",
            "Covers, Tribute Bands": "Music & Concerts"
        }
        cat = category_mapping[category]
        if cat:
            return cat
        print(f"Category Not Found {category}")
        return "Other"